### ISSUE TITLE
take over package maintainership on npm

### ISSUE THREAD

**Issue by mreinstein** [mreinstein/visualizer#1]
hey @waltonseymour I noticed that the `visualizer` package has been deprecated on npm. For the sake of fighting bit rot, I've updated my fork, which moves to pure esm, and gets rid of a _lot_ of noise in the repo files.

I'm wondering if you'd like to:
* give me admin access on the visualizer npm module so that I can update the version

*OR*

* since `visualizer` has no dependents, you could force unpublish the package with

```bash
npm unpublish --force
```

thoughts?

**Comment by waltonseymour** [comment]
hey @mreinstein I've gone ahead and unpublished. The package name is all yours
